### PR TITLE
os-next: one nested APP_CONFIG, password sign-in, boot-time schema, /projects/<slug>/<app> path ingress, the dash connecting to any issuer — the self-hostable platform

### PR DESCRIPTION
**Pull request by jonastemplestein**
One Cloudflare Worker is the whole platform, and this makes it deployable into any Cloudflare account with `wrangler deploy` and two secrets: no domain, no dashboard clicking, no deploy-time migration. Proof-of-concept scope, no backwards compatibility kept.

## What changes

**Configuration is one JSON object**, the `APP_CONFIG` Worker secret (`src/app-config.ts` documents every key; any key is also settable alone as `APP_CONFIG_<PATH>__<KEY>`, a blank var is unset, an unknown key warns):

```js
{
  urls: { os, mcp, dash, ingressRouting: { type: "subdomains", hostname } | { type: "paths" }, temporaryCustomHostnames: {} },
  login: { password, emailCode: { from }, google: { clientId, clientSecret } },   // each on iff present; none ⇒ refuses to boot
  secrets: { key, previousKey, adminBearer },                                      // ONE key: session signing and at-rest encryption derive from it
}
```

**Sign-in mechanisms are the `login` block.** `login.password` is a global password (anyone who knows it signs in as the email they type). It replaces the `424242` test code, which was a global password with a public value, and the admin-bearer `POST /login` sign-in. The specs and e2e sign in with it.

**Boot self-setup.** The directory schema (`control-plane.sql`) is applied by the worker at boot, once per isolate, idempotent. A blank `urls.os` means each request's own origin (the edge remembers the first platform request's; `platform-origin.ts`).

**Projects are reached under one `ingressRouting`.** `subdomains` is today's wildcard. `paths` is new: `https://<os>/projects/<slug>/<app>/…` on the one origin, the prefix stripped before the app sees the URL and said in `x-iterate-base-path`, every answer served with `Content-Security-Policy: sandbox …` so an app on the platform's origin runs in an opaque origin and cannot spend the issuer cookie. One SDK module, `iterate/next/project-ingress`, parses and composes both shapes, table-tested to round-trip; the worker, consent, signed file URLs, the dash and the new `itx.url({ app?, path? })` built-in all use it. `session.info()` carries `ingressRouting`.

**The dash (and agents, notes, voice through the shared adapter) connect to any issuer** — a self-host — through `/.auth/connect`, a same-origin POST page that names the issuer's host and asks. A GET `?issuer=` only lands on that page. Controls per the security review in the task file: issuer normalized to an https origin, no IP/localhost, not under our own zones (`ITERATE_DENY_ZONES`), discovery `issuer` must match, endpoints hand-built, the session record is the sole source of `{ issuer, resource }`, the insecure opt-out keys on the app's origin, no foreign stylesheet on the Sign-in-again page, `platformOrigin`/`mcpOrigin` parsed before any href or command. The shell shows "Connected to <host>". The self-hosted landing page links there.

**Deleted:** `/internal/rpc` (every user dials `/api` with the admin bearer on the upgrade — nothing weakened, a bare POST still gets 401), `/client-icon` and `public/brands` (the consent hero shows initials), `environmentName`, `aiGatewayId`, `recentEphemeralsBudgetChars` (constants beside their consumers), the Artifacts account/namespace vars (the binding's `repo.info().remote` is the URL), the deploy-time schema query, the `prj_` id migration, the retired-secret removal.

**Self-hosting:** `apps/os-next/SELF-HOSTING.md` is the recipe; `wrangler.self-host.jsonc` is generated beside `wrangler.jsonc` (no ids: D1/KV/R2 auto-provision by name).

## LOC

100 files, +3005 / −1311. os-next src +1093/−702 · os-next tests/e2e/specs +544/−312 · SDK +705/−34 (the ingress module + its 44 test rows, the connect page and validator + tests) · dash +70/−10 · scripts/envs/CI +164/−149 · task file +184.

## Risk map

- **`/.auth/connect` and the per-session issuer** (`packages/iterate/src/next/app-server.ts`, `app-session.ts`): the trust boundary. Read `issuerOriginOf`, `held()`, and the `iss`-parameter check that stays hard-coded. Forced login was the exploitable gap the review found; the POST page and `nextPathOf` (strips `issuer` from every `next`) close it.
- **Path ingress sandboxing** (`worker.ts` `sandboxed`, `withoutBasePath`): apps in paths mode have no cookie sign-in (the browser adapter is skipped on that origin) and must authenticate in-band. Correct by construction; the in-band SDK mode is the follow-up.
- **The platform origin at runtime** (`platform-origin.ts`, the `Caller.platformOrigin` field): first-request-wins on a deployment with a blank `urls.os`; a deployment with more than one hostname must set `urls.os` (the parser refuses `urls.mcp` without it).
- **On merge:** Doppler `project-worker` prd and preview_2 already hold the new `APP_CONFIG` and `APP_CONFIG_SECRETS__KEY` (the at-rest key bit-identical, so stored project secrets keep opening). Every browser session signs in once more (the session-signing secret is now derived). The `424242` code stops working on prd; CI derives `LOGIN_PASSWORD` and `ADMIN_API_SECRET` from the blob. Old Worker secrets (`APP_CONFIG_SESSION_SECRET` etc.) become unknown-key warnings until deleted (follow-up).

**Review order:** `app-config.ts` → `project-ingress.ts` (+ test) → `worker.ts` → `app-server.ts` / `app-session.ts` → `control-plane.ts` / `login-code.ts` → `iterate-context*.ts` (the caller carries the platform origin) → scripts, envs, CI → tests, docs.

## Evidence

Local, on this rebase: os-next unit 715 · workers 129 · e2e 226 · Playwright 6 · SDK `next` 77 passed; typecheck (os-next ×3, iterate, dash, agents, notes, voice, root) clean; repo oxlint 0/0; knip clean; format clean. A dry-run `wrangler deploy` accepts both the self-host config and prd's env block. Deployed proof (prd smoke + a real self-hosted deploy with path routing and MCP) follows the merge and is reported on this PR.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---

> [!NOTE]
> **High Risk**
> Changes authentication (password login, removed operator login shortcut), deployment configuration (single APP_CONFIG blob, boot-time schema), and ingress/security (path sandbox, external issuer connect with deny zones)—all security-critical paths requiring careful review of `app-server.ts` and worker ingress.
> 
> **Overview**
> This PR reshapes **os-next** so one Worker can be deployed with two secrets and no deploy-time D1 migration, while first-party apps can point at arbitrary issuers.
> 
> **Configuration** moves to a single `APP_CONFIG` JSON secret (with `APP_CONFIG_*__*` overrides). Sign-in is driven by `login.password` / email / Google; the global `424242` test code and admin-bearer `POST /login` are gone. CI and Depot workflows now pull `ADMIN_API_SECRET` and `LOGIN_PASSWORD` from `APP_CONFIG` at runtime. Deploy no longer runs directory SQL or retires old secret names; the worker applies `control-plane.sql` on first request (new boot-schema test).
> 
> **API surface:** `/internal/rpc` is removed—operators and tests use bare `/api` WebSockets with in-band `admin-secret` (or bearer on upgrade). `/version` reports platform origin instead of environment name. Consent drops `/client-icon` and brand SVGs.
> 
> **Ingress:** `urls.ingressRouting` supports **paths** (`/projects/<slug>/<app>/…`) with CSP sandbox on responses, plus existing subdomains; dash/MCP URLs are validated via `httpOriginOf` and `projectUrlOf`. Self-host gets `SELF-HOSTING.md`, generated `wrangler.self-host.jsonc`, and path-mode defaults.
> 
> **Dash & satellite workers** (`agents`, `notes`, `dash`): `ITERATE_DENY_ZONES` is passed into `appAuth`; the shell shows “Connected to …” when the session issuer differs from default; landing links to dash connect instead of a direct dash href.
> 
> **Tests & specs** are retargeted to `/api`, password login, `ingressHostname()` / `PROJECT_INGRESS_ROUTING`, and a new local-only path-ingress e2e file.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 29d72806dae206daf38a0b7a7174c12256f0a955. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

## Environment Config Lease

> [!CAUTION]
> Tests finished; restoring the clean preview.

<details>
<summary>No preview slot recorded.</summary>

| app | status | commit | preview | size (gzip) | deploy duration | test duration | retries | cleanup duration | workflow run | updated | summary |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Auth | released | `29d7280` | [https://auth.iterate-preview-7.com](https://auth.iterate-preview-7.com) | 855.8 KiB | 27.0s | 31.0s |  | 4.9s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:19:14.768Z | Preview app released. |
| Docs | released | `29d7280` | [https://docs-preview-7.iterate-dev-preview.workers.dev](https://docs-preview-7.iterate-dev-preview.workers.dev) | 1.10 MiB | 20.2s | 4.1s |  | 4.2s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:19:14.055Z | Preview app released. |
| Dummy Petshop | released | `29d7280` | [https://dummy-petshop.iterate-preview-7.com](https://dummy-petshop.iterate-preview-7.com) | 256.0 KiB | 174ms | 9.4s |  | 1.4s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:19:12.416Z | Preview app released. |
| OS | released | `29d7280` | [https://os.iterate-preview-7.com](https://os.iterate-preview-7.com) | 5.42 MiB (-10.8 KiB vs main) | 67.8s | 138.0s | 2 retried: runScript caps an in-script sandbox timeout to its absolute deadline and kills the process group (vitest x1) — {"status":"failed","error":"Sandbox process-group 66 cleanup failed with exit 124: Command timed out after 5000ms","failureKind":"runtime","phase":"execution","executionMayHaveOccurred":true,"cancellation":"external-work-may-continue"}: expected { status: 'failed', …(5) } to match object { status... · mobile/live-status.spec.ts › the live card wears the agent-set status and a phase glyph per round › mobile (playwright x1) — TimeoutError: locator.waitFor: Timeout 1000ms exceeded. Call log: [2m - waiting for getByText('New chat') to be visible[22m [33m Spinner was still visible after 30000ms (or a navigation was still in flight), the UI is likely stuck.[0m | 100.6s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:20:50.470Z | Preview app released. |
| Semaphore | released | `29d7280` | [https://semaphore.iterate-preview-7.com](https://semaphore.iterate-preview-7.com) | 453.8 KiB | 18.9s | 28.1s |  | 1.1s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:19:11.012Z | Preview app released. |
| Streams Example App | released | `29d7280` | [https://streams.iterate-preview-7.com](https://streams.iterate-preview-7.com) | 1.63 MiB | 41.2s | 55.9s |  | 15.0s | [Workflow run](https://github.com/iterate/iterate/actions/runs/4613463426892) | 2026-09-21T17:19:24.892Z | Preview app released. |

</details>

| Group | Lines | Significant |
| --- | ---: | ---: |
| Product | +1,451 -605 | +957 -410 🟩🟩🟩🟩🟥 |
| Tests | +1,177 -505 | +964 -411 🟩🟩🟩🟩🟥 |
| CI & scripts | +142 -128 | +109 -102 🟩⬜⬜⬜⬜ |
| Config | +18 -16 | +18 -16 🟩⬜⬜⬜⬜ |
| Docs | +318 -44 | +280 -43 🟩⬜⬜⬜⬜ |
| Other | +24 -21 | +9 -5 🟩⬜⬜⬜⬜ |
| **Total** | **+3,130 -1,319** | **+2,337 -987** 🟩🟩🟩🟩🟥 |

<sub>Lines counts every changed line; Significant ignores blank lines, JS comments, and TypeScript lines with no runtime output. Between fae2634 and 29d7280, bucketed first-match-wins into the groups defined in `scripts/ci/loc-report.ts`.</sub>

### CODE REVIEW

**Comment by jonastemplestein** [comment]
## Self-hosted deployment proof (this branch, before merge)

Deployed the generated `wrangler.self-host.jsonc` as a NEW Worker into the `iterate (dev/preview)` account with exactly the recipe in `apps/os-next/SELF-HOSTING.md`: one `wrangler deploy --secrets-file` with two minted secrets. D1, both KV namespaces, the R2 bucket and the Artifacts namespace were auto-provisioned by name; the directory schema was applied by the worker on its first request.

`https://iterate-selfhost-poc.iterate-dev-preview.workers.dev`

| Check | Result |
|---|---|
| `/version` | `7418e9da-… https://iterate-selfhost-poc.iterate-dev-preview.workers.dev` (blank `urls.os` ⇒ the request's origin) |
| `/.well-known/oauth-authorization-server` | `issuer` = that origin; S256 |
| `/mcp`, `POST /api` without a bearer | 401, 401 |
| `/login.json` | `{"password":true,"emailSignIn":false,"google":null,"dash":"https://dash.iterate2.com"}` |
| `/` | links `https://dash.iterate2.com/.auth/connect?issuer=…` (the connect page, not a login) |
| `POST /login` wrong password | 303 `?error=That+password+is+not+right.&email=…` (the email kept) |
| `POST /login` right password, empty D1 | 302 + `__Host-itx-session` — boot-time schema works |
| `itx.whoami()` / `itx.url({ app: "echo", path: "/hello" })` | `…/projects/poc-mubgyppu/` · `…/projects/poc-mubgyppu/echo/hello` |
| `GET /projects/<slug>/echo/hello?x=1` (a provided app) | 200 · the app saw `/hello?x=1` · `x-iterate-base-path: /projects/<slug>/echo` · `Content-Security-Policy: sandbox allow-scripts allow-forms allow-popups allow-modals allow-downloads` |
| `GET /<slug>/echo/` (not under `/projects/`) | not a project (302) · `POST /api` still 401 |
| `itx.kv.put/get` | round-trips |

**MCP, the way a client does it** (no browser): `POST /oauth/register` (DCR) → `/authorize` with PKCE S256 and `resource=<origin>/mcp` → `POST /login` with the password → consent over `/api` with the session cookie (`consent.describe`, `createOrg`, `projects.create`, `consent.approve`) → the code came back with `iss` = the origin → `POST /oauth/token` → bearer, `expires_in 3600`, `scope iterate` → `POST /mcp` `initialize` → `{ name: "control-plane" }` → `tools/list` → `["run"]` → `tools/call run` with `async (itx) => ({ who: await itx.whoami(), url: await itx.url({ app: "site" }), kv: … })` → 200, the script ran in the connection's own context (`path: /mcp/inbound/grant_…`) and answered with the project's path-mode URLs and the KV round trip.

The deployed e2e lane is also running against this worker (`WORKER_BASE_URL`, paths routing); result follows.

File: packages/iterate/src/next/app-server.ts [hunk 1]
```diff
@@ -172,7 +465,15 @@ export async function appAuth(request: Request, config: AppAuth): Promise<Respon
...
-        return signInAgainPage({ url, issuer, resource, bearer, scopes: heldScopes, project });
+        return signInAgainPage({
+          url,
+          issuer: target.issuer,
+          resource: target.resource,
+          defaultIssuer: issuer,
+          bearer,
+          scopes: heldScopes,
+          project,
+        });
```
[the remark this answers is not in the document]
Comment (jonastemplestein) [reply packages/iterate/src/next/app-server.ts:476]: Fixed in 041f38e30. `/.auth/login` now starts the fresh session at the issuer the session record held (`target.issuer`), so an expired grant at a self-host signs in again at that self-host; and `/.auth/logout` reads the ended session's issuer first and, when it was not the deployment's own, sends the person through `/.auth/connect?issuer=<that>&next=…` — one click, the host named — rather than a bare `next` that would rebind the browser to the default. Two tests in `app-server.test.ts` pin both ("a browser CONNECTED to another issuer stays there").

File: apps/os-next/src/worker.ts [hunk 2]
```diff
@@ -302,68 +358,41 @@ export default {
...
+    rememberPlatformOrigin(env, url.origin);
+    if (url.origin !== platformOrigin)
       return new Response("Unknown platform origin", { status: 421 });
 
-    // `<deployId> <environmentName>`: Cloudflare's version id of this deploy — the stamp a smoke
-    // waits for (`wrangler deploy` prints it) — and which deployment this is (the app config section below).
-    if (url.pathname === "/version") return new Response(`${deployId} ${environmentName}\n`);
-
-    // Explicit operator fixtures. Public clients authenticate at the HTTP boundary.
-    if (url.pathname === "/internal/rpc") {
```
[the remark this answers is not in the document]
Comment (jonastemplestein) [reply apps/os-next/src/worker.ts:325]: Fixed in 041f38e30. The files host's answer goes through `sandboxed()` under paths ingress exactly as an app's does (`Content-Security-Policy: sandbox …` ⇒ an opaque origin: no cookie to spend, no scripting of the platform's documents). `path-ingress.e2e.test.ts` gained a row: a stored `text/html` page whose script would call `/api`, fetched at its signed `/projects/<slug>/files/…` URL, answers 200 with the sandbox header.

**Comment by jonastemplestein** [comment]
## Deployed e2e lane against the self-hosted worker (paths routing)

`WORKER_BASE_URL=https://iterate-selfhost-poc.iterate-dev-preview.workers.dev … PROJECT_INGRESS_ROUTING='{"type":"paths"}' pnpm e2e`: **215 passed, 18 failed** on the first run.

- **13 failures were the lane's own shape**, not the worker's: rows that compose a project host as `<app>--<slug>.<hostname>` (`ingressHostname()` throws "this row needs subdomain routing" under paths). Real coverage of the same behaviour under paths — an app on a project path, a bearer on it, a WebSocket upgrade, the hop budget, a signed file URL — is the follow-up PR's: those rows compose through `projectUrlOf` and run in both modes.
- **5 failures were a real regression this PR introduced, now fixed in 572c16d31**: `itx.cfArtifacts.get(path)` read the remote URL as a field of the binding's repo handle. Over the service binding that handle is a Workers-RPC stub, so the field is not there (`The RPC receiver does not implement the method "remote"`); `info()` is. The local lanes' fakes carried the field and hid it. Redeployed the POC with the fix: `cfartifacts`, `repos`, `workspaces` and `config-worker` e2e files against real Artifacts — create/get/list/delete, the git round trip through the real remote, a config worker from a real repo — all pass.

CI run 2 (before this fix) was fully green; run 3 is on the way.

File: packages/iterate/src/next/app-server.ts [hunk 3]
```diff
@@ -229,8 +537,12 @@ export async function appAuth(request: Request, config: AppAuth): Promise<Respon
         { status: 503 },
       );
     }
+    const next = nextPathOf(url.searchParams.get("next"), url.origin);
     const headers = new Headers({
-      Location: sameOriginPath(url.searchParams.get("next") || "/", url.origin),
+      Location:
+        ended && ended.issuer !== issuer && !config.loginPage
+          ? `/.auth/connect?${new URLSearchParams({ issuer: ended.issuer, next })}`
```
[the remark this answers is not in the document]
Comment (jonastemplestein) [reply packages/iterate/src/next/app-server.ts]: Fixed in 64fd452c7. The Sign-in-again form's `next` is the login URL that named the scopes (`/.auth/login?…&scope=…`); `/.auth/logout` now reads `scope` from it and puts it on the connect redirect, so the reconnected grant holds what the app asks for and the login goes straight through to `next`. Two rows in `app-server.test.ts` pin it (scopes carried when `next` is the login URL; none when it is an ordinary page).

**Comment by jonastemplestein** [comment]
## prd proof (after merge, deploy 01ba6e406)

**By hand on os.iterate2.com:** `/version` → `<deployId> https://os.iterate2.com`; discovery `issuer` = the origin; `/login.json` → `{"password":true,"emailSignIn":true,"google":true,"dash":"https://dash.iterate2.com"}`; the landing page links `https://dash.iterate2.com/.auth/connect?issuer=https%3A%2F%2Fos.iterate2.com`; `/mcp` and `POST /api` → 401; a wrong password → 303 with the email kept; the right one → 302 + `__Host-itx-session`; `424242` no longer signs anyone in; the dash's connect page is live (the default issuer needs no asking → 303 to its login).

**The deployed e2e lane against prd** (`WORKER_BASE_URL=https://os.iterate2.com`, credentials from the Doppler `APP_CONFIG` exactly as deploy-os-next.yml does): **233 passed, 0 failed** (29 files; 4 expected fails, 20 skipped as designed).

**The merge deploy job itself went red at its LAST step**, after the upload: the routes for `garple.com`, `lispwoso.com`, `templestein.com` could not be added — those zones are not in the prd account (code 10083). The code and every other trigger deployed; #2762 withdraws the three hostnames until the zones move. Retired Worker secrets and the old Doppler names are being deleted now that the lane is green.

**Found on prd and fixed in #2762:** with the password and the mailed code both on, the sign-in page rendered two forms (two Email fields).
